# **Obtención y preparación de datos**
# OD02. Numpy Array

In [ ]:
import numpy as np

### <font color='blue'>**¿Qué es un matriz?**</font>

Una matriz (o arreglo) es la estructura de datos central de la biblioteca NumPy. Una matriz es una cuadrícula de valores y contiene información sobre los datos sin procesar, cómo ubicar un elemento y cómo interpretar un elemento. Tiene una cuadrícula de elementos que se pueden indexar de varias formas. Los elementos son todos del mismo tipo, denominados `array dtype`.

<img src='https://drive.google.com/uc?export=view&id=1gzNzhv_B2Dcu5NzozSAXqmNp3zio6Mc1' width="500" align="center" style="margin-right: 20px">

**Nota: es posible referirse la estructura `ndarray` de NumPy de las siguientes formas: array, arreglo, y/o matriz.**

Una matriz puede ser indexada por una tupla de enteros no negativos, por booleanos, por otra matriz o por enteros. El rango de la matriz es el número de dimensiones. La forma de la matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Una forma en que podemos inicializar matrices NumPy es a partir de listas de Python, utilizando listas anidadas para datos bidimensionales o de mayor dimensión. Por ejemplo:


In [ ]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


In [ ]:
A = np.array(["a", "b", "c"])
print(A)

['a' 'b' 'c']


o

In [ ]:
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])
print(A)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


Podemos acceder a los elementos de la matriz utilizando **corchetes**. Cuando acceda a los elementos de la matriz, recuerde que la **indexación en NumPy comienza en 0**. Eso significa que si desea acceder al primer elemento de su matriz, estará accediendo al elemento "0".

<img src='https://drive.google.com/uc?export=view&id=18qtkEag596pYiUWuULj1f88v4L-1DEnq' width="500" align="center" style="margin-right: 20px">

In [ ]:
print(A[:,2])

[ 3  9 15 21]


# <font color='purple'>**Experimento**</font><br>

El siguiente código es un complemento de las funcionalidades de Numpy con el Array A

In [ ]:


#El siguiente código sirve para seleccionar la segunda fila de nuestro objeto A
print(A[1,:])


# Seleccionar la tercera columna
print("Tercera columna:", A[:, 2])

# Seleccionar un submatriz (las dos primeras filas y dos primeras columnas)
submatrix = A[:2, :2]
print("Submatriz (2x2):\n", submatrix)

# Sumar 10 a cada elemento
print("A + 10:\n", A + 10)

# Elevar al cuadrado cada elemento
print("A^2:\n", A ** 2)

# Calcular la suma de todos los elementos
print("Suma de los elementos:", np.sum(A))

# Media de cada columna
print("Media de cada columna:", np.mean(A, axis=0))

# Máximo y mínimo de toda la matriz
print("Máximo:", np.max(A))
print("Mínimo:", np.min(A))

# Desviación estándar
print("Desviación estándar:", np.std(A))

# Seleccionar elementos mayores a 10
mayores_a_10 = A[A > 10]
print("Elementos mayores a 10:", mayores_a_10)

# Reemplazar valores menores a 10 por 0
A[A < 10] = 0
print("Matriz modificada:\n", A)

# Transponer la matriz
print("Transpuesta:\n", A.T)

# Cambiar la forma de la matriz (reshape)
B = A.reshape(2, 6)
print("Matriz reshaped (2x6):\n", B)

[7 8 9]
Tercera columna: [ 3  9 15 21]
Submatriz (2x2):
 [[1 2]
 [7 8]]
A + 10:
 [[11 12 13]
 [17 18 19]
 [23 24 25]
 [29 30 31]]
A^2:
 [[  1   4   9]
 [ 49  64  81]
 [169 196 225]
 [361 400 441]]
Suma de los elementos: 132
Media de cada columna: [10. 11. 12.]
Máximo: 21
Mínimo: 1
Desviación estándar: 6.757711644237764
Elementos mayores a 10: [13 14 15 19 20 21]
Matriz modificada:
 [[ 0  0  0]
 [ 0  0  0]
 [13 14 15]
 [19 20 21]]
Transpuesta:
 [[ 0  0 13 19]
 [ 0  0 14 20]
 [ 0  0 15 21]]
Matriz reshaped (2x6):
 [[ 0  0  0  0  0  0]
 [13 14 15 19 20 21]]


### <font color='purple'>**Fin Experimento**</font><br>

In [ ]:
print(A[0,2])

0


In [ ]:
print(A[2,1])

14


Una matriz N-dimensional es una matriz con cualquier número de dimensiones. También puede encontrar matrices 1D o matriz unidimensional, 2D o matriz bidimensional, etc.

La clase `ndarray` de NumPy se utiliza para representar tanto matrices como vectores. Un vector es una matriz con una sola dimensión (no hay diferencia entre los vectores de fila y columna), mientras que una matriz se refiere a una matriz con dos dimensiones. Para matrices tridimensionales o superiores, el término tensor también se usa comúnmente.

#### <font color='blue'>**¿Cuáles son los atributos de una matriz?**</font>

Una matriz suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. El número de dimensiones y elementos de una matriz se define por su forma. La forma de una matriz es una tupla de números enteros no negativos que especifican los tamaños de cada dimensión.

En NumPy, las dimensiones se llaman ejes. Esto significa que si tiene una matriz 2D que se ve así:

In [ ]:
[[0., 0., 0.],
 [1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

Su matriz tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.

Al igual que en otros objetos contenedores de Python, se puede acceder y modificar el contenido de una matriz indexando o dividiendo (_slicing_) la matriz. A diferencia de los objetos contenedores típicos, diferentes matrices pueden compartir los mismos datos, por lo que los cambios realizados en una matriz pueden ser visibles en otra.

Los atributos de la matriz reflejan información intrínseca a la propia matriz. Si necesita obtener, o incluso establecer, propiedades de una matriz sin crear una nueva matriz, a menudo puede acceder a una matriz a través de sus atributos. Para detalles y más información vea la documentación oficial de [ndarray](https://numpy.org/devdocs/reference/arrays.ndarray.html#arrays-ndarray).

## <font color='green'>**Actividad 1**</font>

A partir de la matriz A definida anteriomente:

```python
A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])
```

1. Indicar el rango y la forma de la matriz _A_.
1. Crear un vector *a1* que corresponda a la segunda columna de la matriz _A_.
1. Crear una matriz *a2* que incluya los elementos de las filas 2 a 4 y de las columnas 2 a 3 de la matriz A.
1. Crear un vector *a3* que contenga los elementos $A[0,0], A[1,2], A[0,1], A[3,2], A[2,2]$ y $A[1,1]$
1. Crear una matriz *a4* de 2x3 con las primeras dos filas.
1. Crear una matriz *a5* que contenga la última y la primera fila de la matriz A.

In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])

A

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [ ]:
A.shape
np.linalg.matrix_rank(A)

##rango de un arreglo son las dimensiones

2

In [ ]:
# Tu código aquí ...

import numpy as np

A = np.array([[1, 2, 3], [7, 8, 9], [13, 14, 15], [19, 20, 21]])

# 1. Obtener el rango y la forma de la matriz A

rango = np.linalg.matrix_rank(A)  # Rango de la matriz A
forma = A.shape  # Forma de la matriz A

print(f"Rango de la matriz A: {rango}")
print(f"Forma de la matriz A: {forma}")

# 2. Crear un vector a1 que corresponda a la segunda columna de la matriz A
a1 = A[:, 1]  # Segunda columna (índice 1)

print(f"Vector a1 (segunda columna de A): {a1}")

# 3. Crear una matriz a2 que incluya los elementos de las filas 2 a 4 y de las columnas 2 a 3 de la matriz A

a2 = A[1:4, 1:3]  # Filas 2 a 4 (índices 1 a 3) y columnas 2 a 3 (índices 1 a 2)

print(f"Matriz a2 (filas 2 a 4, columnas 2 a 3):\n{a2}")

# 4. Crear un vector a3 con los elementos A[0,0], A[1,2], A[0,1], A[3,2], A[2,2], A[1,1]
a3 = np.array([A[0, 0], A[1, 2], A[0, 1], A[3, 2], A[2, 2], A[1, 1]])

print(f"Vector a3 con elementos específicos: {a3}")

# 5. Crear una matriz a4 de 2x3 con las primeras dos filas de A
a4 = A[0:2, :]  # Primeras dos filas (índices 0 y 1) y todas las columnas

print(f"Matriz a4 (2x3, primeras dos filas):\n{a4}")

# 6. Crear una matriz a5 que contenga la última y la primera fila de A
a5 = A[[3, 0], :]  # Última fila (índice 3) y primera fila (índice 0)

print(f"Matriz a5 (última y primera fila):\n{a5}")

Rango de la matriz A: 2
Forma de la matriz A: (4, 3)
Vector a1 (segunda columna de A): [ 2  8 14 20]
Matriz a2 (filas 2 a 4, columnas 2 a 3):
[[ 8  9]
 [14 15]
 [20 21]]
Vector a3 con elementos específicos: [ 1  9  2 21 15  8]
Matriz a4 (2x3, primeras dos filas):
[[1 2 3]
 [7 8 9]]
Matriz a5 (última y primera fila):
[[19 20 21]
 [ 1  2  3]]


<font color='green'>**Fin actividad 1**</font>

#<font color='purple'>**MATERIAL ADICIONAL**</font><br>

NumPy es una de las bibliotecas más poderosas y fundamentales en el ecosistema de Python para trabajar con datos numéricos. Los arrays de NumPy son una extensión de las listas tradicionales de Python, diseñados para realizar cálculos más rápidos y eficientes gracias a su implementación en C. Su estructura homogénea permite almacenar datos de un único tipo, lo que facilita operaciones matemáticas vectorizadas, reduciendo la necesidad de bucles explícitos que mejoran el rendimiento.

Una característica fascinante de NumPy es el "broadcasting", que permite realizar operaciones aritméticas entre arrays de diferentes tamaños. Por ejemplo, sumar un array 1D a cada fila de un array 2D sin necesidad de bucles explícitos. Esto es especialmente útil en análisis de datos y en el procesamiento de imágenes, donde se necesita aplicar una transformación uniforme a toda una matriz de píxeles.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
print(A + B)  # Broadcasting suma B a cada fila de A

[[11 22 33]
 [14 25 36]]


NumPy incluye herramientas avanzadas como la Transformada de Fourier (FFT), que se utiliza en análisis de señales, procesamiento de audio y compresión de imágenes. Es un excelente ejemplo de cómo NumPy se aplica a problemas del mundo real.

In [ ]:
from numpy.fft import fft
signal = np.array([1, 2, 3, 4])
print("Transformada de Fourier:\n", fft(signal))

Transformada de Fourier:
 [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


NumPy facilita el análisis de grandes volúmenes de datos como imágenes, datos meteorológicos y simulaciones científicas. Por ejemplo, arrays tridimensionales pueden representar imágenes en color (altura, ancho, canales RGB) o datos volumétricos, simplificando su manipulación.

**Fuentes:**

Documentación oficial de NumPy - Para aprender desde lo básico hasta técnicas avanzadas.

https://numpy.org/doc/stable/index.html

SciPy Lectures - Tutoriales completos para entender NumPy y su ecosistema.

https://lectures.scientific-python.org/

NumPy Broadcasting Documentation - Explicación detallada del concepto de broadcasting.

https://numpy.org/doc/stable/user/basics.broadcasting.html

Estos conceptos destacan la versatilidad de NumPy y cómo su uso puede extenderse a diversas áreas del conocimiento.

# <font color='purple'>**FIN MATERIAL ADICIONAL**</font><br>