# **Obtención y preparación de datos**
# OD03. Creación de Array

In [ ]:
import numpy as np

## <font color='blue'>**Creando vectores y matrices** </font>

Para crear una matriz NumPy, se puede utilizar la función `np.array()`.

Todo lo que necesita hacer para crear una matriz simple es pasarle una lista. Si lo desea, también puede especificar el tipo de datos en su lista.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4, 5, 6]])
c = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(a)
print()
print(b)
print()
print(c)
c.shape

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
# Especificamos el tipo de los datos
d = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]], dtype=np.float64)
print(d)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


# <font color='purple'>**EXPERIMENTO**</font><br>

**Experimento: Creación de Arrays y Comportamiento del Tipo de Dato Más Complejo**

Vamos a explorar cómo NumPy maneja la homogeneidad de los datos en un array y por qué selecciona el tipo más complejo cuando se combinan diferentes tipos de datos.

In [ ]:
import numpy as np

# Array con mezcla: número primero, luego string
array_mixed_1 = np.array([1, 2, "Hola"])
print("Array (número primero):", array_mixed_1)
print("Tipo de dato del array:", array_mixed_1.dtype)

# Array con mezcla: string primero, luego número
array_mixed_2 = np.array(["Hola", 1, 2])
print("\nArray (string primero):", array_mixed_2)
print("Tipo de dato del array:", array_mixed_2.dtype)

# Array con mezcla: booleano y número
array_mixed_3 = np.array([True, 42])
print("\nArray (booleano y número):", array_mixed_3)
print("Tipo de dato del array:", array_mixed_3.dtype)

# Array con mezcla: flotante y entero
array_mixed_4 = np.array([1.5, 2])
print("\nArray (flotante e entero):", array_mixed_4)
print("Tipo de dato del array:", array_mixed_4.dtype)

Array (número primero): ['1' '2' 'Hola']
Tipo de dato del array: <U21

Array (string primero): ['Hola' '1' '2']
Tipo de dato del array: <U21

Array (booleano y número): [ 1 42]
Tipo de dato del array: int64

Array (flotante e entero): [1.5 2. ]
Tipo de dato del array: float64


**Resultados y Explicación**

**Tipo de dato más complejo:**

Cuando se mezclan tipos de datos en un array, NumPy convierte todos los elementos al tipo más complejo dentro del conjunto. En el caso de ["Hola", 1, 2], convierte todo a tipo str porque los strings tienen mayor complejidad que números o booleanos.

**Orden de complejidad de tipos:** NumPy sigue una jerarquía de tipos basada en su capacidad de representar datos:

**bool → int → float → complex → str → object.**

Por ejemplo, si mezclas bool y int, el array será int, porque int puede representar True y False como 1 y 0.

**Conversión automática según el tipo más complejo:**

En np.array([True, 42]), el booleano se convierte a entero (True → 1), y el dtype final es int.

En np.array([1.5, 2]), el entero se convierte a flotante (2 → 2.0), y el dtype final es float.

**Caso especial:** *object:* Si los datos no se pueden convertir a un tipo común (como listas y strings), NumPy usará el tipo object:

In [ ]:
import numpy as np

array_object = np.array([1, "Hola", [1, 2]], dtype=object)
print("\nArray con listas y strings:", array_object)
print("Tipo de dato del array:", array_object.dtype)


Array con listas y strings: [1 'Hola' list([1, 2])]
Tipo de dato del array: object


**¿Por qué NumPy elige el tipo más complejo?**

NumPy prioriza la preservación de la información. Si los datos se convirtieran al tipo más simple, habría pérdida de información:

Por ejemplo, convertir 1.5 a *int* resultaría en pérdida de la parte decimal.
En cambio, convertir un *int* a *float* mantiene intacto el valor.

**¿Alguna vez elige un tipo más simple?**

No, NumPy siempre eleva al tipo más complejo para garantizar que todos los valores puedan ser representados correctamente dentro del array.

**Conclusión**

Este comportamiento de NumPy es esencial para garantizar la coherencia y la integridad de los datos en operaciones vectorizadas. Sin embargo, también implica que es importante planificar el tipo de datos antes de crear arrays, especialmente al trabajar con grandes volúmenes de datos donde los tipos más complejos podrían impactar en la eficiencia.

# <font color='purple'>**FIN EXPERIMENTO**</font><br>

Además de crear una matriz a partir de una secuencia de elementos, puede crear fácilmente un vector o una matriz llena de ceros:

In [ ]:
vector_ceros = np.zeros(5)
matriz_ceros = np.zeros((2,5))
print(vector_ceros)
print()
print(matriz_ceros)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


o un vector o matriz de 1s:

In [ ]:
vector_unos = np.ones(5)
matriz_unos = np.ones((2,5))
print(vector_unos)
print()
print(matriz_unos)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


o un vector o matriz vacía. La función vacía crea una matriz cuyo contenido inicial es aleatorio y depende del estado de la memoria. La razón para usar vacío sobre ceros (o algo similar) es la velocidad, ¡solo asegúrese de completar todos los elementos después!.

In [ ]:
np.empty(5)

array([4.97674752e-310, 0.00000000e+000, 0.00000000e+000, 1.27864189e-320,
       2.37151510e-322])

También es posible crear un vector con elementos dentro de un rango:

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

Un vector que contiene un rango de intervalos espaciados uniformemente. Para hacer esto, debe especificar el primer número, el último número y el tamaño del paso.

In [ ]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

También puede utilizar `np.linspace()` para crear una matriz con valores espaciados linealmente en un intervalo especificado:

In [ ]:
np.linspace(0, 15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

El tipo de datos predeterminado es punto flotante (*np.float64*), pero es posible especificar explícitamente qué tipo de datos desea, utilizando la palabra clave `dtype`. Para más información sobre tipo de datos, refiera a la documentación oficial de [arrays-dtypes](https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes).

In [ ]:
x = np.ones(5, dtype=np.int64)
x

array([1, 1, 1, 1, 1])

La __matriz de identidad__ es una matriz cuadrada con unos en la diagonal principal:

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# <font color='purple'>**MATERIAL ADICIONAL**</font><br>

Al revisar la documentación, nos percatamos que np.indentity() es un alias para la función np.eye() con exactamente la misma funcionalidad.

De hecho, la definición [es de la siguiente forma](https://github.com/numpy/numpy/blob/v1.9.1/numpy/core/numeric.py#L2125):


```
def identity(n, dtype=None):
    from numpy import eye
    return eye(n, dtype=dtype)
```


# <font color='purple'>**FIN MATERIAL ADICIONAL**</font><br>




## <font color='blue'>**Operaciones con matrices**</font>

Las operaciones básicas son simples con NumPy. Una vez que ha creado sus matrices, puede comenzar a trabajar con ellas. Por ejemplo, se han creado dos matrices, una llamada *a* y otra llamada *b*.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 3, 6, 8, 1], dtype=int)
a + b

array([11,  5,  9, 12,  6])

Si desea encontrar la suma de los elementos en una matriz, debe usar **sum()**. Esto funciona para matrices 1D, matrices 2D y matrices en dimensiones más altas.

In [ ]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [ ]:
matriz_unos.sum()

10.0

Para realizar esta operación en más dimensiones, debe especificar el eje.

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
print()
print(b.shape)

[[0 1 2]
 [3 4 5]]

(2, 3)


Para sumar por filas:

In [ ]:
b.sum(axis=0)

array([3, 5, 7])

cuando decimos axis 0 nos referimos a las filas, las filas cuando queremos sumarlas, queremos que desaparezcan las filas, es como que estuvieramos poniendo una mano, aplastando las filas, que quede 1 sola fila. El axis 1 es desaparezcan las columnas. Filas sumando la vertical

__IMPORTANTE__: Cuando establecemos `axis = 0`, la función en realidad suma las columnas. El resultado es una nueva matriz NumPy que contiene la suma de cada columna. ¿Por qué? ¿El eje 0 no se refiere a las filas?

Esto confunde a muchos principiantes. El parámetro `axis` nos indica qué eje será colapsado (desaparece). Es decir, cuando definimos `axis=0`, `np.sum()`colapsa las filas de la matriz y calcula las sumas.


<img src='https://drive.google.com/uc?export=view&id=1VYCaccao-3x7ePrUvM9TFUB4wyaxybxm' width="200" align="center" style="margin-right: 20px">

Entonces, cuando establecemos el `axis = 0`, no estamos sumando las filas. Cuando establecemos el `axis = 0`, estamos agregando los datos de modo que colapsamos las filas... colapsamos el eje 0.




Para sumar por columnas:

In [ ]:
b.sum(axis=1)

array([ 3, 12])

In [ ]:
d = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]], dtype=np.float64)
e = d = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]], dtype=np.float64)

d.sum(axis=1)

(2, 3)

In [ ]:
d+e

array([[[ 2.,  4.,  6.],
        [ 8., 10., 12.]],

       [[14., 16., 18.],
        [20., 22., 24.]]])

In [ ]:
d.sum(axis=1).shape

Veamos qué ocurre cuando usamos `axis = 1`. Nuevamente, el parámetro `axis` establece el eje que se colapsa durante el proceso, en este caso, la suma.

El eje `axis = 1` se refiere a la dirección horizontal a través de las columnas. Eso significa que el código `b.sum(axis = 1)` colapsa las columnas durante la suma.

<img src='https://drive.google.com/uc?export=view&id=1uA5db6c9Jz2r30iA_9QOo1s75aSUEBiz' width="300" align="center" style="margin-right: 20px">


Sustracción:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 3, 6, 8, 1], dtype=int)
a - b

array([-9, -1, -3, -4,  4])

Multiplicación por elementos:

In [ ]:
a = np.array( [[1,1],[2,1]] )
b = np.array( [[2,4],[3,4]] )
print(a)
print(b)
a * b

[[1 1]
 [2 1]]
[[2 4]
 [3 4]]


array([[2, 4],
       [6, 4]])

Multiplicación de matrices: se puede realizar utilizando el operador `@` (en Python $\ge$ 3.5) o la función o método `dot`:

In [ ]:
a @ b

array([[ 5,  8],
       [ 7, 12]])

In [ ]:
a.dot(b)

array([[ 5,  8],
       [ 7, 12]])

División:

In [ ]:
a / b

array([[0.5       , 0.25      ],
       [0.66666667, 0.25      ]])

Otras operaciones:

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)
# Elevar a una potencia
c = b**2
print(c)
print()
# Función seno
c = 10 * np.sin(a)
print(c)
print()
# Funciones lógicas
c = a < 35
print(c)

[0 1 4 9]

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]

[ True  True False False]


In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
# Mínimo
b = a.min()
print(b)
print()
# Máximo
b = a.max()
print(b)
print()
# Máximo por columna
b = a.max(axis=1)
print(b)
print()
# Media
b = a.mean()
print(b)
print()
# Desviación estándar
b = a.std()
print(b)
print()

0.05093587

0.82485143

[0.5510652  0.55645993 0.82485143]

0.4049648666666667

0.21392120766089617



NumPy contiene una batería de operaciones sobre matrices: aritméticas, operaciones binarias, estadísticas, funciones, entre otras. Para más información, vea la [guía de uso rápido de Numpy](https://numpy.org/devdocs/user/quickstart.html#the-basics).

La generación de números aleatorios es una parte importante en la configuración y evaluación de muchos algoritmos de aprendizaje automático. Ya sea que necesite inicializar pesos aleatoriamente en una red neuronal artificial, dividir datos en conjuntos aleatorios o mezclar aleatoriamente su conjunto de datos, es esencial poder generar números aleatorios (en realidad, números pseudoaleatorios repetibles).

Con la clase `Generator`de Numpy, puede acceder a una amplia gama de métodos para generar números aleatorios. Vemos un ejemplo para generar una matriz de 2 x 4 de números enteros aleatorios entre 0 y 4:

In [ ]:
# De esta forma creamos el generador con el BitGenerator por defecto (PCG64)
np.random.default_rng()

Generator(PCG64) at 0x786A8996B220

In [ ]:
# Instanciamos el generador
rng = np.random.default_rng()

# Creamos un arreglo de números aleatorios entre 0 y 4 de tamaño 2x4
rng.integers(5, size=(2, 4))

array([[0, 2, 1, 1],
       [2, 3, 3, 4]])

Veamos otro ejemplo:

In [ ]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

Algunas operaciones, como `+=` y `*=`, actúan para modificar una matriz existente en lugar de crear una nueva.

In [ ]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
print(a)
print()
b += a
print(b)

[[3 3 3]
 [3 3 3]]

[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


Es posible realizar una operación entre una matriz y un solo número (operación entre un vector y un escalar) o entre matrices de dos tamaños diferentes. Por ejemplo:

In [ ]:
distancia_millas = np.array([1.0, 2.0])
distancia_km = distancia_millas * 1.6
print(distancia_km)

[1.6 3.2]


### <font color='green'>Actividad 1</font>

1. Crear una matriz de 4x9 que esté inicializada con el valor 3.5.
2. Crear un vector de longitud 4.
3. Crear una matriz identidad de tamaño 4.


In [ ]:
# Tu código aquí ...
import numpy as np


matriz_4x9 = np.full((4, 9), 3.5)
print("Matriz 4x9 inicializada con 3.5:")
print(matriz_4x9)

# Crear un vector de longitud 4
vector_4 = np.zeros(4) # aquí la inicializo en 0.

#vector_4 = np.ndarray(4)
print("\nVector de longitud 4:")
print(vector_4)


matriz_identidad_4 = np.eye(4)

print("\nMatriz identidad de tamaño 4:")
print(matriz_identidad_4)

Matriz 4x9 inicializada con 3.5:
[[3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]]

Vector de longitud 4:
[0. 0. 0. 0.]

Matriz identidad de tamaño 4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<font color='green'>Fin actividad 1</font>

### <font color='green'>Actividad 2</font>

1. Crear una matriz de dos dimensiones en que una dimensión represente el sexo y la otra la edad de los integrantes del grupo. Luego, convertir la dimensión edad en años a la edad en meses.
1. Generar una matriz de 7 por 9. Las primeras 3 columnas de la matriz tienen que tener el valor 0. La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7. Las otras cinco columnas deben tener el valor 1.

In [ ]:
# Tu código aquí ...
import numpy as np


# 0 representa 'femenino', 1 representa 'masculino'
grupo = np.array([
    [0, 26],  # Mujer de 25 años
    [1, 30],  # Hombre de 30 años
    [1, 40],  # Hombre de 40 años
    [1, 34]   # Hombre de 34 años
])

print("Matriz original (Sexo, Edad en años):")
print(grupo)

# Convertir la edad en años a meses (multiplicar por 12)
grupo[:, 1] = grupo[:, 1] * 12

print("\nMatriz después de convertir la edad a meses:")
print(grupo)

Matriz original (Sexo, Edad en años):
[[ 0 26]
 [ 1 30]
 [ 1 40]
 [ 1 34]]

Matriz después de convertir la edad a meses:
[[  0 312]
 [  1 360]
 [  1 480]
 [  1 408]]


In [ ]:

matriz_7x9 = np.ones((7, 9))  # Inicializar con 1s
matriz_7x9[:, :3] = 0         # Las primeras 3 columnas con valor 0
matriz_7x9[:, 3] = 0.5        # La cuarta columna con valor 0.5
matriz_7x9[-1, 3] = 0.7       # El último valor de la cuarta columna con valor 0.7

print("\nMatriz 7x9 generada:")
print(matriz_7x9)


Matriz 7x9 generada:
[[0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.5 1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.7 1.  1.  1.  1.  1. ]]


<font color='green'>Fin actividad 2</font>

<img src="https://drive.google.com/uc?export=view&id=1DNuGbS1i-9it4Nyr3ZMncQz9cRhs2eJr" width="100" align="left" title="Runa-perth">
<br clear="left">

## <font color='blue'>**Resumen**</font>

`numpy` es una de las bibliotecas más esenciales en el ecosistema de Python cuando se trata de cálculos numéricos y análisis de datos. Es especialmente útil para operaciones que involucran arrays o matrices, proporcionando una interfaz eficiente y optimizada. La capacidad de `numpy` para trabajar con datos de alta dimensión y realizar operaciones de forma vectorizada la convierte en una herramienta indispensable para científicos de datos, ingenieros y programadores.




#### Crear un array básico

In [ ]:
# Crear un array 1D
a = np.array([1, 2, 3, 4])
print(a)

# Crear un array 2D (Matriz)
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]


#### Arrays con Valores Específicos

In [ ]:
# Ceros
print(np.zeros((3, 4)))

# Unos
print(np.ones((2, 3)))

# Valor constante
print(np.full((2, 2), 7))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


#### Arrays Basados en Rangos y Espacios

In [ ]:
# Valores en un rango
print(np.arange(0, 10, 2))

# Valores espaciados linealmente
print(np.linspace(0, 1, 5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


#### Matrices Especiales

In [ ]:
# Matriz identidad
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Arrays con Valores Aleatorios

In [ ]:
# Valores aleatorios entre 0 y 1
print(np.random.rand(2, 3))

# Valores aleatorios de una distribución normal estándar
print(np.random.randn(2, 3))

[[0.88543814 0.03802147 0.67840425]
 [0.64293548 0.56273163 0.49510559]]
[[ 0.61852394 -2.6881426  -0.14337258]
 [ 1.28438671 -0.47278816  1.27296518]]


#### Manipulación de la Forma de un Array

In [ ]:
# Obtener las dimensiones
h = np.array([[1, 2], [3, 4], [5, 6]])
print("Forma de h:", h.shape)

# Cambiar la forma
i = np.array([1, 2, 3, 4, 5, 6])
j = i.reshape(2, 3)
print(j)

Forma de h: (3, 2)
[[1 2 3]
 [4 5 6]]


<img src="https://drive.google.com/uc?export=view&id=1DNuGbS1i-9it4Nyr3ZMncQz9cRhs2eJr" width="50" align="left" title="Runa-perth">
<br clear="left">

# <font color='purple'>**MATERIAL ADICIONAL**</font><br>

Los dtypes (tipos de datos) en NumPy determinan el tipo de valor que puede almacenar cada elemento en un array. A diferencia de las listas estándar de Python, donde los elementos pueden ser heterogéneos, los arrays de NumPy están optimizados para almacenar datos homogéneos, es decir, todos los elementos deben ser del mismo tipo. Esto permite aprovechar las capacidades de bajo nivel de NumPy para realizar cálculos más rápidos y con menor uso de memoria.

Algunos de los dtypes más comunes incluyen:

**int:** Números enteros.

**float:** Números de punto flotante.

**complex:** Números complejos.

**bool:** Valores booleanos (True/False).

**str:** Cadenas de texto.

**object:** Cualquier tipo de objeto de Python (menos común en NumPy).




In [ ]:
import numpy as np

#Ejemplo de cómo especificar un dtype:

# Crear un array con dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)
print("Array:", arr)
print("Tipo de dato:", arr.dtype)

Array: [1 2 3]
Tipo de dato: int32


**Ventajas de los dtypes de NumPy**

**Eficiencia en Memoria:** Puedes definir tipos de datos específicos para optimizar el uso de memoria. Por ejemplo, int8 usa menos memoria que int32.

**Rendimiento Mejorado:** Al trabajar con un solo dtype, NumPy realiza cálculos más rápido, aprovechando operaciones vectorizadas en bajo nivel.

**Compatibilidad:** Es posible manejar datos científicos y binarios de manera precisa, como imágenes (usando uint8) o datos de sensores.

NumPy también permite definir tipos de datos compuestos (estructurados), similares a un diccionario o estructura en otros lenguajes de programación. Esto es útil para trabajar con datos tabulares o estructurados.

In [ ]:
# Definir un dtype personalizado
person_dtype = np.dtype([('name', 'S20'), ('age', 'int32'), ('weight', 'float32')])

# Crear un array con el dtype personalizado
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 72.5)], dtype=person_dtype)

print(people)
print("Nombre del primero:", people[0]['name'])

[(b'Alice', 25, 55. ) (b'Bob', 30, 72.5)]
Nombre del primero: b'Alice'


NumPy facilita la conversión entre tipos de datos mediante el método .astype():

In [ ]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)

# Convertir a enteros
int_arr = arr.astype(np.int32)
print("Array convertido:", int_arr)

Array convertido: [1 2 3]


Esto es esencial para ajustar la precisión o preparar datos para modelos de machine learning.

**Aplicaciones de los dtypes**

**Procesamiento de Imágenes:** Los arrays de tipo uint8 son comunes para representar imágenes, ya que almacenan valores entre 0 y 255.

**Simulación Científica:** Los tipos float64 y complex128 son ideales para cálculos científicos que requieren alta precisión.

**Big Data:** Reducir el tamaño de los datos con tipos como int8 puede ser crucial al procesar grandes volúmenes de información.

Comprender los dtypes de NumPy no solo mejora la eficiencia de las aplicaciones, sino que también permite trabajar con datos de manera más precisa y flexible. Este conocimiento es fundamental para desarrollar proyectos que involucran grandes volúmenes de datos o cálculos intensivos.

**Fuentes para profundizar:**

https://www.geeksforgeeks.org/numpy-data-types/


# <font color='purple'>**FIN MATERIAL ADICIONAL**</font><br>